### PR TITLE
[Draft] Qadence 2 monorepo

### PR DESCRIPTION
**Pull request by kaosmicadei**
Add submodules:
- [x] Qadence 2 - IR
- [x] Qadence 2 - Expressions
- [ ] Qadence 2 - Platforms

### CODE REVIEW

**Review by Roland-djee — COMMENTED** [review]
Hey @kaosmicadei, is it necessary to do that ? Can we just get away with adding dependencies ?

**Comment by kaosmicadei** [comment]
> is it necessary to do that ? Can we just get away with adding dependencies ?

It's a bit safer than dependencies.

**Comment by Roland-djee** [comment]
> > is it necessary to do that ? Can we just get away with adding dependencies ?
> 
> It's a bit safer than dependencies.

Yeah but you have to execute an extra command to install them right ?

**Comment by kaosmicadei** [comment]
> > > is it necessary to do that ? Can we just get away with adding dependencies ?
> 
> > 
> 
> > It's a bit safer than dependencies.
> 
> 
> 
> Yeah but you have to execute an extra command to install them right ?

Yes, for now (which is definitely not ideal)

Actually, this shouldn't be merged with the `main` branch but with some `dev` branch. What do you think?

**Comment by Roland-djee** [comment]
> > > > is it necessary to do that ? Can we just get away with adding dependencies ?
> > 
> > 
> > > 
> > 
> > 
> > > It's a bit safer than dependencies.
> > 
> > 
> > Yeah but you have to execute an extra command to install them right ?
> 
> Yes, for now (which is definitely not ideal)
> 
> Actually, this shouldn't be merged with the `main` branch but with some `dev` branch. What do you think?

I don't know. It feels redundant with the dependencies and less controllable. Since dependencies are monitored by Renovate, It feels quite safe for now. I assume we can move to submodules if hatch finally doesn't support monorepos in the long run.

**Comment by Roland-djee** [comment]
Closing as agreed @kaosmicadei.

**Pull request closed without merging**
